version: "3"

services:
  # nombre del servicio
  mongodb:
    image: mongo
    container_name: mongo_db_container_swagger
    ports:
      # local --> contenedor
      - 27018:27017
    restart: always
    

  api:
    build: .
    container_name: api_containerr_swagger
    ports:
      # local --> contenedor
      - 6000:6000
    depends_on:
      - mongodb
    restart: always
    # opcional ya que ayuda a desarrollar con el docker compose ejecutandose
    volumes:
      - .:/usr/src/app